apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: effx
build:
  local:
    concurrency: 2
    useBuildkit: true
    useDockerCLI: true

  tagPolicy:
    sha256: {}

  artifacts:
    - image: cluster-agent
      docker:
        dockerfile: ./Dockerfile
      sync:
        infer:
          - "main.go"
          - "internal/**/*"

deploy:
  helm:
    releases:
      # effx services (abc)
      - name: cluster-agent
        chartPath: deploy
        namespace: effx
        skipBuildDependencies: true
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: cluster-agent
        valuesFiles:
          - deploy/values-{{ .APP_ENV }}.yaml

portForward:
  - resourceType: Service
    resourceName: cluster-agent
    namespace: effx
    port: 8080
    localPort: 8105
