name: Release

on:
  push:
    tags:
      - v*

jobs:
  container:
    name: Publish Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        run: echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin ${REGISTRY_HOST}
        env:
          REGISTRY_USERNAME: ${{ secrets.GHCR_REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.GHCR_REGISTRY_PUSH_PASSWORD }}
          REGISTRY_HOST: ghcr.io

      - name: Build Container Image
        env:
          REGISTRY_HOST: ghcr.io
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ${REGISTRY_HOST}/effxhq/cluster-agent:latest \
            --tag ${REGISTRY_HOST}/effxhq/cluster-agent:${GITHUB_REF##*/v} \
            -f Dockerfile \
            --push

  chart:
    name: Publish Chart
    runs-on: ubuntu-latest

    needs:
      - container

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare
        run: |
          sudo apt-get install wget
          wget https://github.com/mikefarah/yq/releases/download/v4.9.7/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Set Versions
        run:
          /usr/bin/yq e ".version = \"${GITHUB_REF##*/v}\"" -i ./deploy/cluster-agent/Chart.yaml
          /usr/bin/yq e ".appVersion = \"${GITHUB_REF##*/v}\"" -i ./deploy/cluster-agent/Chart.yaml

      # TODO: Setup GPG signing
      # - name: Prepare GPG key
      #   run: |
      #     gpg_dir=.cr-gpg
      #     mkdir "$gpg_dir"

      #     keyring="$gpg_dir/secring.gpg"
      #     base64 -d <<< "$GPG_KEYRING_BASE64" > "$keyring"

      #     passphrase_file="$gpg_dir/passphrase"
      #     echo "$GPG_PASSPHRASE" > "$passphrase_file"

      #     echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
      #     echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
      #   env:
      #     GPG_KEYRING_BASE64: "${{ secrets.GPG_KEYRING_BASE64 }}"
      #     GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"

      # - name: Add dependency chart repos
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: deploy
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.CHART_RELEASER_TOKEN }}"
